language: node_js

jobs:
  include:
      
    # test node module
    - script: npm test
      node_js:
        - "10"
        - "8"
        - "6"
    
    # compile documents  
    - stage: docs
      node_js: "6"
      script:
          
        # install Pandoc
        - curl -fLo /tmp/pandoc-2.2.1-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
        - sudo dpkg -i /tmp/pandoc-2.2.1-1-amd64.deb

        # install Pandoc::Elements
        - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
        - sudo cpanm --notest Pandoc::Elements

        # create documents
        - mkdir -p dist/mode
        - npm run spec

      deploy:
        on:
          branch: master
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
